# Generated by Django 4.1.2 on 2023-03-26 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('emp_id', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(6)])),
                ('emp_role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Employee')], default=2)),
            ],
        ),
    ]
